# Generated by Django 2.0.7 on 2018-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(help_text='单位是便士')),
                ('logo', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('show', models.BooleanField(default=1)),
                ('type2', models.CharField(default='self', max_length=5)),
            ],
        ),
    ]
